### ISSUE TITLE
Signaling WouldBlock with empty data?

### ISSUE THREAD

**Issue by dvtomas** [berkowski/mio-serial#12]
Hi,
I'm a little bit confused about how a `WouldBlock` is signalled.

[Mio doc states:](https://docs.rs/mio/0.6.16/mio/struct.Poll.html)

*With edge-triggered events, operations must be performed on the Evented type until WouldBlock is returned. In other words, after receiving an event indicating readiness for a certain operation, one should assume that Poll::poll may never return another event for the same token and readiness until the operation returns WouldBlock.*

But your [example](https://github.com/berkowski/mio-serial/blob/master/examples/serial_printline.rs) goes like this:

```rust
match rx.read(&mut rx_buf) {
	Ok(b) => match b {
		b if b > 0 => {
			println!("{:?}", String::from_utf8_lossy(&rx_buf[..b]))
		}
		_ => println!("Read would have blocked."),
	},
	Err(e) => println!("Error:  {}", e),
}
```

i.e. it seems that blocking, and thus a signal that we can stop performing read on the serial port, is signaled via empty data. Is this a behavior not obeying the specs, or just me misunderstanding something?

On a related note: In your example is this:

```rust
if is_closed(ready) {
	println!("Quitting due to event: {:?}", ready);
	break 'outer;
}
```

Can I decide not to handle `is_closed()` explicitly, and just rely on `rx.read()` returning an error if the port becomes closed?

**Comment by berkowski** [comment]
The mio docs state that for edge-triggered read operations the client should read until a WouldBlock error.  The default match case where b <= 0 should never be triggered because b will always have a size of at least one.  However, we still need the guard on the match case or rust will throw an error at compile time.  The logic could be more clear if I changed the println! to something like panic!.

For the second part:  It does look like you can just catch the error on read, and then check what type of error was raised .

**Comment by dvtomas** [comment]
Ok, in that case, is the guard on bytes count necessary at all? Also, according to MIO docs, with edge-triggered events we ought loop reading until a WouldBlock is received. Maybe this kind of example (replacing the part I've quoted in the first post) would be more correct? Or is there anything special about mio-serial MIO semantics?

```rust
loop {
    // With edge triggered events, we must perform reading until we receive a WouldBlock
    match rx.read(&mut rx_buf) {
        Ok(b) => println!("{:?}", String::from_utf8_lossy(&rx_buf[..b])),
        Err(ref e) if e.kind() == io::ErrorKind::WouldBlock => {
            break;
        }
        Err(e) => {
            println!("Error:  {}", e)
            break;
        },
    }
}
```

**Comment by dvtomas** [comment]
Hi, @berkowski ,

if you find time, what is your opinion on my last comment? We're implementing communication with measurement devices that needs to be pretty reliable, so I need to be sure about the correct way to use mio-serial. I've had issues before with TCP communication freeze when I didn't loop until WouldBlock, that's why I've raised the question with the example I think would be a proper way to handle MIO compatbile Evented read stream..

**Comment by berkowski** [comment]
@dvtomas

Sorry about the delay.  I'm on a ship at the moment and internet access is pretty..... slow....

Your example code seems like it would work (minus the small missing ';' after the second prinln!).  I swapped in your method in the example and didn't see any change using the signals I can easily generate here at the moment.

My own knowledge of the internals of mio are limited to what their docs were about a year ago and it looks like they've put in a lot more work there since my last read.  I don't think there is much difference between the two methods in practice, but your version certainly reads better and seems more idomatic.

**Comment by dvtomas** [comment]
Cool, thank you for your investigation. Should I update the docs with my example and make a PR? Maybe even replacing `println!("Error..")` with `panic!` would better show the intent..

Enjoy your sail!

**Comment by berkowski** [comment]
I'd welcome a PR with those changes :)  Otherwise I'll get around to it when I'm back on shore in December.
